services:
  python_app:
    container_name: python-loja
    build:
      context: ./
      dockerfile: python.dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8001:8000"
    volumes:
      - ./:/usr/src/app
    restart: always
    tty: true
    networks:
      - python-loja-network

  mysql:
    container_name: python-loja-mysql
    image: mysql
    volumes:
      - ../volumes/python-loja/mysql/:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - python-loja-network

networks:
  python-loja-network:
    driver: bridge