services:
  python_app:
    container_name: python-loja
    build:
      context: ./
      dockerfile: python.dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8001:8000"
    volumes:
      - ./:/usr/src/app
    restart: always
    tty: true
    networks:
      - python-loja-network


networks:
  python-loja-network:
    driver: bridge